// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

#pragma once
#ifndef WINRT_WordCounter_H
#define WINRT_WordCounter_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.220929.3"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.220929.3"
#include "winrt/impl/Microsoft.UI.Xaml.2.h"
#include "winrt/impl/Microsoft.UI.Xaml.Markup.2.h"
#include "winrt/impl/WordCounter.2.h"
namespace winrt::impl
{
    template <typename D>
    struct produce<D, winrt::WordCounter::IMainWindow> : produce_base<D, winrt::WordCounter::IMainWindow>
    {
    };
}
WINRT_EXPORT namespace winrt::WordCounter
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::WordCounter::IMainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::WordCounter::MainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::WordCounter::XamlMetaDataProvider> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
