// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

void* winrt_make_WordCounter_MainWindow()
{
    return winrt::detach_abi(winrt::make<winrt::WordCounter::factory_implementation::MainWindow>());
}
WINRT_EXPORT namespace winrt::WordCounter
{
    MainWindow::MainWindow() :
        MainWindow(make<WordCounter::implementation::MainWindow>())
    {
    }
}
