// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

void* winrt_make_WordCounter_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::WordCounter::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::WordCounter
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<WordCounter::implementation::XamlMetaDataProvider>())
    {
    }
}
